# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: cc67a272da69b9be6d15e8fe81961d2125579432abc5b27e664aa527ded0f195d13aa3bc547596b5679e3929bcec87f3a222c73904b077ec3641ed131bace8ec

test:
  secret_key_base: d2c9206e40c82801b73d31369c9d7805911f993896909ba0f82de86c27a0404837f47c9c2d726c38d641983f7c749cb51f350b390c5692648e191a58a836262a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
